#!/bin/sh


PATH=/sbin:/bin:/usr/sbin:/usr/bin
runlevel=S
prevlevel=N
umask 022
export PATH runlevel prevlevel

mount -a
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts
#mount -n -t usbfs none /proc/bus/usb
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s
mkdir -p /var/lock

ifconfig lo 127.0.0.1

/bin/hostname -F /etc/sysconfig/HOSTNAME

ifconfig eth0 10.0.0.2
mkdir -p share
mount -t nfs -o nolock 10.0.0.1:/home/sheldon.liu/linux-qemu-lab-arm/root_nfs/share   /share